# Generated by Django 3.2.5 on 2021-07-08 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(db_column='name', max_length=45, null=True)),
                ('company_password', models.CharField(db_column='password', max_length=45, null=True)),
                ('company_description', models.TextField(db_column='description', null=True)),
                ('company_sector', models.CharField(db_column='sector', max_length=45, null=True)),
                ('company_country', models.CharField(db_column='country', max_length=45, null=True)),
                ('company_street', models.CharField(db_column='street', max_length=45, null=True)),
                ('company_city', models.CharField(db_column='city', max_length=45, null=True)),
                ('company_st_number', models.IntegerField(db_column='number', null=True)),
                ('company_postal_code', models.IntegerField(db_column='postal_code', null=True)),
                ('n_employees', models.IntegerField(db_column='number_of_employees', null=True)),
                ('company_website', models.URLField(db_column='website', null=True)),
            ],
            options={
                'db_table': 'company',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(db_column='username', max_length=45, null=True, unique=True)),
                ('user_password', models.CharField(db_column='password', max_length=45, null=True)),
                ('user_name', models.CharField(db_column='name', max_length=45, null=True)),
                ('last_name1', models.CharField(db_column='1st_last_Name', max_length=45, null=True)),
                ('last_name2', models.CharField(db_column='2nd_last_name', max_length=45, null=True)),
                ('user_age', models.IntegerField(db_column='age', null=True)),
                ('user_email', models.CharField(db_column='email', max_length=45, null=True)),
                ('user_number', models.BigIntegerField(db_column='mobile_number', null=True)),
                ('user_education', models.CharField(db_column='education', max_length=45, null=True)),
                ('user_volunteer', models.CharField(db_column='volunteer_work', max_length=45, null=True)),
                ('user_country', models.CharField(db_column='country', max_length=45, null=True)),
                ('user_street', models.CharField(db_column='street', max_length=45, null=True)),
                ('user_st_number', models.IntegerField(db_column='number', null=True)),
                ('user_city', models.CharField(db_column='city', max_length=45, null=True)),
                ('user_postal_code', models.IntegerField(db_column='postal_code', null=True)),
                ('user_CV', models.TextField(db_column='cv', null=True)),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='Work_Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(db_column='username', max_length=45, null=True)),
                ('job_title', models.CharField(db_column='job_title', max_length=45, null=True)),
                ('company', models.CharField(db_column='company', max_length=45, null=True)),
                ('duration', models.FloatField(db_column='duration_years', null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.user')),
            ],
            options={
                'db_table': 'work_experience',
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(db_column='company_names', max_length=45, null=True)),
                ('job_title', models.CharField(db_column='job_title', max_length=45, null=True)),
                ('job_description', models.TextField(db_column='job_description', null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.company')),
            ],
            options={
                'db_table': 'job',
            },
        ),
    ]
