# Generated by Django 3.2.5 on 2021-07-08 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='company_name',
            field=models.CharField(db_column='name', max_length=45, null=True, unique=True),
        ),
    ]
