# Generated by Django 3.2.5 on 2021-07-13 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_alter_company_company_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_CV',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_education',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_volunteer',
        ),
        migrations.AddField(
            model_name='user',
            name='user_company',
            field=models.CharField(db_column='company', max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='user_job_description',
            field=models.CharField(db_column='job_description', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='user_job_duration',
            field=models.CharField(db_column='duration', max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='user_job_position',
            field=models.CharField(db_column='job_position', max_length=45, null=True),
        ),
    ]
