# Generated by Django 3.2.5 on 2021-07-13 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_auto_20210713_1254'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_date_registered',
            field=models.DateTimeField(db_column='date_registered', null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name1',
            field=models.CharField(db_column='last_name1', max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name2',
            field=models.CharField(db_column='last_name2', max_length=45, null=True),
        ),
    ]
