# Generated by Django 3.2.5 on 2021-07-15 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_auto_20210714_1643'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_company',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_job_description',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_job_duration',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_job_position',
        ),
    ]
